queue_rules:
  - name: default
    conditions:
      - status-success=complete-pr
pull_request_rules:
  - name: L10N - Auto Merge
    conditions:
      - and:
        - files~=(strings.xml|l10n.toml)
        - or:
          - and:
            - author=mozilla-l10n-automation-bot
            - base=main
            - status-success=complete-pr
          - and:
            - author=github-actions[bot]
            - base~=releases[_/].*
            # Taskcluster doesn't run when PRs are created by github-actions[bot]
            # because it's not considered a collaborator.
    actions:
      review:
        type: APPROVE
        message: LGTM 😎
      queue:
        method: rebase
        name: default
        rebase_fallback: none
  - name: Needs landing - Rebase
    conditions:
      - base=main
      - label=🛬 needs landing
      - "#approved-reviews-by>=1"
      - -draft
    actions:
      queue:
        method: rebase
        name: default
        rebase_fallback: none
  - name: Needs landing - Squash
    conditions:
      - base=main
      - label=🛬 needs landing (squash)
      - "#approved-reviews-by>=1"
      - -draft
    actions:
      queue:
        method: squash
        name: default
        rebase_fallback: none
  - name: Relbot - Auto Merge
    conditions:
      - base=main
      - files~=AndroidComponents.kt
      - author=github-actions[bot]
    actions:
      review:
        type: APPROVE
        message: ✅ Cleared to land.
      queue:
        method: rebase
        name: default
        rebase_fallback: none
  - name: Relbot - delete head branch after merge
    conditions:
      - author=github-actions[bot]
      - merged
    actions:
      delete_head_branch:
