# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 0
allowPullRequests: public
tasks:
###############################################################################
# Task: Pull requests
###############################################################################
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.edited
          - pull_request.synchronize
          - pull_request.reopened
    scopes:
      - "queue:create-task:aws-provisioner-v1/github-worker"
      - "queue:scheduler-id:taskcluster-github"
    payload:
      maxRunTime: 1800
      deadline: "{{ '2 hours' | $fromNow }}"
      image: 'mozillamobile/focus-android'
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git fetch {{ event.head.repo.url }} {{ event.head.repo.branch }}
          && git config advice.detachedHead false
          && git checkout {{event.head.sha}}
          && pip install taskcluster
          && python /opt/focus-android/tools/taskcluster/schedule-screenshots.py
      artifacts:
        'public':
          type: 'directory'
          path: '/opt/focus-android/app/build/reports'
          expires: "{{ '1 week' | $fromNow }}"
      features: {
        "taskclusterProxy": true
      }
    metadata:
      name: Focus for Android - Screenshots decision task
      description: Task for scheduling sub tasks that create screenshots in different locales
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
