# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 0
allowPullRequests: public
tasks:
###############################################################################
# Task: Pull requests
###############################################################################
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.edited
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 3600
      deadline: "{{ '2 hours' | $fromNow }}"
      image: 'mozillamobile/focus-android'
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git fetch {{ event.head.repo.url }} {{ event.head.repo.branch }}
          && git config advice.detachedHead false
          && git checkout {{event.head.sha}}
          && export ADJUST_TOKEN_FOCUS='..no..value..'
          && ./gradlew clean assemble test lint pmd checkstyle findbugs
      artifacts:
        'public':
          type: 'directory'
          path: '/opt/focus-android/app/build/reports'
          expires: "{{ '1 week' | $fromNow }}"
    metadata:
      name: Focus for Android - Build - Pull Request
      description: Building Focus for Android (via Gradle) - triggered by a pull request.
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
###############################################################################
# Task: Master builds
###############################################################################
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      deadline: "{{ '2 hours' | $fromNow }}"
      image: 'mozillamobile/focus-android'
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git fetch origin
          && git config advice.detachedHead false
          && git checkout {{event.head.sha}}
          && export ADJUST_TOKEN_FOCUS='..no..value..'
          && ./gradlew clean assemble test lint pmd checkstyle findbugs
      artifacts:
        'public':
          type: 'directory'
          path: '/opt/focus-android/app/build/reports'
          expires: "{{ '1 week' | $fromNow }}"
    metadata:
      name: Focus for Android - Build - Master
      description: Building Focus for Android (via Gradle) - Master
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
