codecov:
  max_report_age: off

comment: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
       threshold: 0.1
       if_not_found: success
    patch:
      default:
        # Patch ensures X percent of added lines are covered by unit tests.
        # However, we don't require unit tests for each commit so it doesn't
        # make sense to enable patch checks.
        enabled: no
        threshold: 0.1
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
