
basepath = "."

locales = [
  "ace",
  "af",
  "am",
  "an",
  "anp",
  "ar",
  "ast",
  "ay",
  "az",
  "bg",
  "bn-BD",
  "bn-IN",
  "bo",
  "bs",
  "ca",
  "cak",
  "co",
  "cs",
  "cy",
  "da",
  "de",
  "dsb",
  "el",
  "en-CA",
  "eo",
  "es-AR",
  "es-CL",
  "es-ES",
  "es-MX",
  "eu",
  "fa",
  "fi",
  "fr",
  "fy-NL",
  "ga-IE",
  "gl",
  "gu-IN",
  "he",
  "hi-IN",
  "hr",
  "hsb",
  "hu",
  "hus",
  "hy-AM",
  "ia",
  "id",
  "it",
  "ixl",
  "ja",
  "jv",
  "ka",
  "kab",
  "kk",
  "ko",
  "kw",
  "lo",
  "lt",
  "meh",
  "mix",
  "mr",
  "ms",
  "my",
  "nb-NO",
  "ne-NP",
  "nl",
  "nn-NO",
  "nv",
  "oc",
  "pa-IN",
  "pai",
  "pl",
  "ppl",
  "pt-BR",
  "quc",
  "quy",
  "ro",
  "ru",
  "sk",
  "sl",
  "sn",
  "sq",
  "sr",
  "su",
  "sv-SE",
  "ta",
  "te",
  "th",
  "tr",
  "trs",
  "tsz",
  "tt",
  "uk",
  "ur",
  "vi",
  "wo",
  "yua",
  "zam",
  "zh-CN",
  "zh-HK",
  "zh-TW",
  ]
[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
